//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using BespokedBikes.Application.Generated;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace BespokedBikes.Api.Controllers
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IController
    {

        /// <summary>
        /// Create a new customer
        /// </summary>


        /// <returns>Customer created successfully</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<CustomerDto>> CreateCustomerAsync(CustomerDto body);

        /// <summary>
        /// Search customers
        /// </summary>


        /// <returns>List of customers</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<CustomerDto>>> SearchCustomersAsync(string? searchTerm = null);

        /// <summary>
        /// Get customer by ID
        /// </summary>


        /// <returns>Customer details</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<CustomerDto>> GetCustomerByIdAsync(System.Guid id);

        /// <summary>
        /// Update customer
        /// </summary>


        /// <returns>Customer updated successfully</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<CustomerDto>> UpdateCustomerAsync(System.Guid id, CustomerDto body);

        /// <summary>
        /// Create a new employee
        /// </summary>


        /// <returns>Employee created successfully</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<EmployeeDto>> CreateEmployeeAsync(EmployeeDto body);

        /// <summary>
        /// List employees
        /// </summary>


        /// <returns>List of employees</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<EmployeeDto>>> ListEmployeesAsync(Location? location = null, EmployeeRole? role = null);

        /// <summary>
        /// Get employee by ID
        /// </summary>


        /// <returns>Employee details</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<EmployeeDto>> GetEmployeeByIdAsync(System.Guid id);

        /// <summary>
        /// Update employee
        /// </summary>


        /// <returns>Employee updated successfully</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<EmployeeDto>> UpdateEmployeeAsync(System.Guid id, EmployeeDto body);

        /// <summary>
        /// Create a new product
        /// </summary>


        /// <returns>Product created successfully</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<ProductDto>> CreateProductAsync(ProductDto body);

        /// <summary>
        /// List products
        /// </summary>

        /// <returns>List of products</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<ProductDto>>> ListProductsAsync();

        /// <summary>
        /// Get product by ID
        /// </summary>


        /// <returns>Product details</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<ProductDto>> GetProductByIdAsync(System.Guid id);

        /// <summary>
        /// Update product
        /// </summary>


        /// <returns>Product updated successfully</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<ProductDto>> UpdateProductAsync(System.Guid id, ProductDto body);

        /// <summary>
        /// Update product inventory
        /// </summary>


        /// <returns>Inventory updated successfully</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<InventoryDto>> UpdateProductInventoryAsync(System.Guid id, InventoryUpdateDto body);

        /// <summary>
        /// Create a new sale
        /// </summary>


        /// <returns>Sale created successfully</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<SaleDto>> CreateSaleAsync(CreateSaleDto body);

        /// <summary>
        /// Get sales by date range
        /// </summary>



        /// <returns>List of sales</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<SaleDto>>> GetSalesByDateRangeAsync(System.DateTimeOffset? startDate = null, System.DateTimeOffset? endDate = null, SaleStatus? status = null);

        /// <summary>
        /// Get sale by ID
        /// </summary>


        /// <returns>Sale details</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<SaleDto>> GetSaleByIdAsync(System.Guid id);

        /// <summary>
        /// Get quarterly commission report
        /// </summary>


        /// <returns>Quarterly commission report</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<QuarterlyCommissionReportDto>> GetQuarterlyCommissionsAsync(int year, int quarter);

        /// <summary>
        /// Get employee quarterly commission report
        /// </summary>



        /// <returns>Employee quarterly commission report</returns>

        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<EmployeeCommissionDto>> GetEmployeeQuarterlyCommissionsAsync(System.Guid id, int year, int quarter);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]

    public partial class Controller : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IController _implementation;

        public Controller(IController implementation)
        {
            _implementation = implementation;
        }

        /// <summary>
        /// Create a new customer
        /// </summary>
        /// <returns>Customer created successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api/customers")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<CustomerDto>> CreateCustomer([Microsoft.AspNetCore.Mvc.FromBody] CustomerDto body)
        {

            return _implementation.CreateCustomerAsync(body);
        }

        /// <summary>
        /// Search customers
        /// </summary>
        /// <returns>List of customers</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/customers")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<CustomerDto>>> SearchCustomers([Microsoft.AspNetCore.Mvc.FromQuery] string? searchTerm = null)
        {

            return _implementation.SearchCustomersAsync(searchTerm);
        }

        /// <summary>
        /// Get customer by ID
        /// </summary>
        /// <returns>Customer details</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/customers/{id}")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<CustomerDto>> GetCustomerById(System.Guid id)
        {

            return _implementation.GetCustomerByIdAsync(id);
        }

        /// <summary>
        /// Update customer
        /// </summary>
        /// <returns>Customer updated successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/customers/{id}")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<CustomerDto>> UpdateCustomer(System.Guid id, [Microsoft.AspNetCore.Mvc.FromBody] CustomerDto body)
        {

            return _implementation.UpdateCustomerAsync(id, body);
        }

        /// <summary>
        /// Create a new employee
        /// </summary>
        /// <returns>Employee created successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api/employees")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<EmployeeDto>> CreateEmployee([Microsoft.AspNetCore.Mvc.FromBody] EmployeeDto body)
        {

            return _implementation.CreateEmployeeAsync(body);
        }

        /// <summary>
        /// List employees
        /// </summary>
        /// <returns>List of employees</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/employees")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<EmployeeDto>>> ListEmployees([Microsoft.AspNetCore.Mvc.FromQuery] Location? location = null, [Microsoft.AspNetCore.Mvc.FromQuery] EmployeeRole? role = null)
        {

            return _implementation.ListEmployeesAsync(location, role);
        }

        /// <summary>
        /// Get employee by ID
        /// </summary>
        /// <returns>Employee details</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/employees/{id}")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<EmployeeDto>> GetEmployeeById(System.Guid id)
        {

            return _implementation.GetEmployeeByIdAsync(id);
        }

        /// <summary>
        /// Update employee
        /// </summary>
        /// <returns>Employee updated successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/employees/{id}")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<EmployeeDto>> UpdateEmployee(System.Guid id, [Microsoft.AspNetCore.Mvc.FromBody] EmployeeDto body)
        {

            return _implementation.UpdateEmployeeAsync(id, body);
        }

        /// <summary>
        /// Create a new product
        /// </summary>
        /// <returns>Product created successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api/products")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<ProductDto>> CreateProduct([Microsoft.AspNetCore.Mvc.FromBody] ProductDto body)
        {

            return _implementation.CreateProductAsync(body);
        }

        /// <summary>
        /// List products
        /// </summary>
        /// <returns>List of products</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/products")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<ProductDto>>> ListProducts()
        {

            return _implementation.ListProductsAsync();
        }

        /// <summary>
        /// Get product by ID
        /// </summary>
        /// <returns>Product details</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/products/{id}")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<ProductDto>> GetProductById(System.Guid id)
        {

            return _implementation.GetProductByIdAsync(id);
        }

        /// <summary>
        /// Update product
        /// </summary>
        /// <returns>Product updated successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/products/{id}")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<ProductDto>> UpdateProduct(System.Guid id, [Microsoft.AspNetCore.Mvc.FromBody] ProductDto body)
        {

            return _implementation.UpdateProductAsync(id, body);
        }

        /// <summary>
        /// Update product inventory
        /// </summary>
        /// <returns>Inventory updated successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/products/{id}/inventory")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<InventoryDto>> UpdateProductInventory(System.Guid id, [Microsoft.AspNetCore.Mvc.FromBody] InventoryUpdateDto body)
        {

            return _implementation.UpdateProductInventoryAsync(id, body);
        }

        /// <summary>
        /// Create a new sale
        /// </summary>
        /// <returns>Sale created successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api/sales")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<SaleDto>> CreateSale([Microsoft.AspNetCore.Mvc.FromBody] CreateSaleDto body)
        {

            return _implementation.CreateSaleAsync(body);
        }

        /// <summary>
        /// Get sales by date range
        /// </summary>
        /// <returns>List of sales</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/sales")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.ICollection<SaleDto>>> GetSalesByDateRange([Microsoft.AspNetCore.Mvc.FromQuery] System.DateTimeOffset? startDate = null, [Microsoft.AspNetCore.Mvc.FromQuery] System.DateTimeOffset? endDate = null, [Microsoft.AspNetCore.Mvc.FromQuery] SaleStatus? status = null)
        {

            return _implementation.GetSalesByDateRangeAsync(startDate, endDate, status);
        }

        /// <summary>
        /// Get sale by ID
        /// </summary>
        /// <returns>Sale details</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/sales/{id}")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<SaleDto>> GetSaleById(System.Guid id)
        {

            return _implementation.GetSaleByIdAsync(id);
        }

        /// <summary>
        /// Get quarterly commission report
        /// </summary>
        /// <returns>Quarterly commission report</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/reports/commissions/quarterly")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<QuarterlyCommissionReportDto>> GetQuarterlyCommissions([Microsoft.AspNetCore.Mvc.FromQuery] int year, [Microsoft.AspNetCore.Mvc.FromQuery] int quarter)
        {

            return _implementation.GetQuarterlyCommissionsAsync(year, quarter);
        }

        /// <summary>
        /// Get employee quarterly commission report
        /// </summary>
        /// <returns>Employee quarterly commission report</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/reports/commissions/employee/{id}/quarterly")]
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<EmployeeCommissionDto>> GetEmployeeQuarterlyCommissions(System.Guid id, [Microsoft.AspNetCore.Mvc.FromQuery] int year, [Microsoft.AspNetCore.Mvc.FromQuery] int quarter)
        {

            return _implementation.GetEmployeeQuarterlyCommissionsAsync(id, year, quarter);
        }

    }

    


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765